Public Class 前傳
    Dim t1 As Integer = 0
    Dim t2 As Integer = 0
    'Private Declare Function ShowCursor Lib "user32" (ByVal bShow As Long) As Long
    Private Sub Form1_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        WindowState = FormWindowState.Maximized
        FormBorderStyle = FormBorderStyle.None
        'ShowCursor(0)
        Windows.Forms.Cursor.Hide()
        T1穿越伊始.Enabled = True

    End Sub
    Sub PlayBackgroundSoundResource()
        My.Computer.Audio.Play(My.Resources.戀愛循環__online_audio_converter_com_, AudioPlayMode.Background)
    End Sub
    Sub PlaylightSoundResource()
        My.Computer.Audio.Play(My.Resources.電燈開關__online_audio_converter_com_, AudioPlayMode.Background)
    End Sub
    Sub PlaybirdSoundResource()
        My.Computer.Audio.Play(My.Resources.蟲鳴鳥叫__online_audio_converter_com_, AudioPlayMode.Background)
    End Sub
    Sub PlaywakeupSoundResource()
        My.Computer.Audio.Play(My.Resources.鬧鐘, AudioPlayMode.Background)
    End Sub

    Private Sub T1穿越伊始_Tick(sender As Object, e As EventArgs) Handles T1穿越伊始.Tick

        t1 = t1 + 1

        Dim A(800) As Integer
        A(1) = 1
        For i = 2 To 26
            A(i + 1) = A(i) + 2
        Next i
        For i = 27 To 28
            A(i + 1) = A(i) + 15
        Next i
        For i = 29 To 31
            A(i + 1) = A(i) + 10
        Next i
        For i = 32 To 41
            A(i + 1) = A(i) + 2
        Next i
        For i = 42 To 650
            A(i + 1) = A(i) + 1
        Next i
        '  For i = 244 To 244
        '  A(i + 1) = A(i) + 30
        '   Next i
        '  For i = 245 To 245
        '  A(i + 1) = A(i) + 4
        '  Next i

        If t1 = A(1) Then
            PictureBox1.Image = My.Resources._1_28
        ElseIf t1 = A(2) Then
            PictureBox1.Image = My.Resources._1_27
        ElseIf t1 = A(3) Then
            PictureBox1.Image = My.Resources._1_26
        ElseIf t1 = A(4) Then
            PictureBox1.Image = My.Resources._1_25
        ElseIf t1 = A(5) Then
            PictureBox1.Image = My.Resources._1_24
        ElseIf t1 = A(6) Then
            PictureBox1.Image = My.Resources._1_23
        ElseIf t1 = A(7) Then
            PictureBox1.Image = My.Resources._1_22
        ElseIf t1 = A(8) Then
            PictureBox1.Image = My.Resources._1_21
        ElseIf t1 = A(9) Then
            PictureBox1.Image = My.Resources._1_20
            PlaybirdSoundResource()
        ElseIf t1 = A(10) Then
            PictureBox1.Image = My.Resources._1_19
        ElseIf t1 = A(11) Then
            PictureBox1.Image = My.Resources._1_18
        ElseIf t1 = A(12) Then
            PictureBox1.Image = My.Resources._1_17
        ElseIf t1 = A(13) Then
            PictureBox1.Image = My.Resources._1_16
        ElseIf t1 = A(14) Then
            PictureBox1.Image = My.Resources._1_15
        ElseIf t1 = A(15) Then
            PictureBox1.Image = My.Resources._1_14
        ElseIf t1 = A(16) Then
            PictureBox1.Image = My.Resources._1_13
        ElseIf t1 = A(17) Then
            PictureBox1.Image = My.Resources._1_12
        ElseIf t1 = A(18) Then
            PictureBox1.Image = My.Resources._1_11
        ElseIf t1 = A(19) Then
            PictureBox1.Image = My.Resources._1_10
        ElseIf t1 = A(20) Then
            PictureBox1.Image = My.Resources._1_9
        ElseIf t1 = A(21) Then
            PictureBox1.Image = My.Resources._1_8
        ElseIf t1 = A(22) Then
            PictureBox1.Image = My.Resources._1_7
        ElseIf t1 = A(23) Then
            PictureBox1.Image = My.Resources._1_6
        ElseIf t1 = A(24) Then
            PictureBox1.Image = My.Resources._1_5
        ElseIf t1 = A(25) Then
            PictureBox1.Image = My.Resources._1_4
        ElseIf t1 = A(26) Then
            PictureBox1.Image = My.Resources._1_3
        ElseIf t1 = A(27) Then
            PlaywakeupSoundResource()
            PictureBox1.Image = My.Resources._1_2
        ElseIf t1 = A(28) Then
            PictureBox1.Image = My.Resources._1_2
        ElseIf t1 = A(29) Then
            PlaylightSoundResource()
            PictureBox1.Image = My.Resources._1_1
        ElseIf t1 = A(30) Then
            PlaylightSoundResource()
            PictureBox1.Image = My.Resources._1_0
        ElseIf t1 = A(31) Then
            PictureBox1.Image = My.Resources._1_0
        ElseIf t1 = A(32) Then
            PlayBackgroundSoundResource()
            PictureBox1.Image = My.Resources._3_1
        ElseIf t1 = A(33) Then
            PictureBox1.Image = My.Resources._3_2
        ElseIf t1 = A(34) Then
            PictureBox1.Image = My.Resources._3_3
        ElseIf t1 = A(35) Then
            PictureBox1.Image = My.Resources._3_4
        ElseIf t1 = A(36) Then
            PictureBox1.Image = My.Resources._3_5
        ElseIf t1 = A(37) Then
            PictureBox1.Image = My.Resources._3_6
        ElseIf t1 = A(38) Then
            PictureBox1.Image = My.Resources._3_7
        ElseIf t1 = A(39) Then
            PictureBox1.Image = My.Resources._3_8
        ElseIf t1 = A(40) Then
            PictureBox1.Image = My.Resources._3_9
        ElseIf t1 = A(41) Then
            PictureBox1.Image = My.Resources._3_10
        ElseIf t1 = A(42) Then
            PictureBox1.Image = My.Resources._3_11
        ElseIf t1 = A(43) Then
            PictureBox1.Image = My.Resources._3_12
        ElseIf t1 = A(44) Then
            PictureBox1.Image = My.Resources._3_13
        ElseIf t1 = A(45) Then
            PictureBox1.Image = My.Resources._3_14
        ElseIf t1 = A(46) Then
            PictureBox1.Image = My.Resources._3_15
        ElseIf t1 = A(47) Then
            PictureBox1.Image = My.Resources._3_16
        ElseIf t1 = A(48) Then
            PictureBox1.Image = My.Resources._3_17
        ElseIf t1 = A(49) Then
            PictureBox1.Image = My.Resources._3_18
        ElseIf t1 = A(50) Then
            PictureBox1.Image = My.Resources._3_19
        ElseIf t1 = A(51) Then
            PictureBox1.Image = My.Resources._3_20
        ElseIf t1 = A(52) Then
            PictureBox1.Image = My.Resources._3_21
        ElseIf t1 = A(53) Then
            PictureBox1.Image = My.Resources._3_22
        ElseIf t1 = A(54) Then
            PictureBox1.Image = My.Resources._3_23
        ElseIf t1 = A(55) Then
            PictureBox1.Image = My.Resources._3_24
        ElseIf t1 = A(56) Then
            PictureBox1.Image = My.Resources._3_25
        ElseIf t1 = A(57) Then
            PictureBox1.Image = My.Resources._3_26
        ElseIf t1 = A(58) Then
            PictureBox1.Image = My.Resources._3_27
        ElseIf t1 = A(59) Then
            PictureBox1.Image = My.Resources._4_1
        ElseIf t1 = A(60) Then
            PictureBox1.Image = My.Resources._4_2
        ElseIf t1 = A(61) Then
            PictureBox1.Image = My.Resources._4_3
        ElseIf t1 = A(62) Then
            PictureBox1.Image = My.Resources._4_4
        ElseIf t1 = A(63) Then
            PictureBox1.Image = My.Resources._4_5
        ElseIf t1 = A(64) Then
            PictureBox1.Image = My.Resources._4_6
        ElseIf t1 = A(65) Then
            PictureBox1.Image = My.Resources._4_7
        ElseIf t1 = A(66) Then
            PictureBox1.Image = My.Resources._4_8
        ElseIf t1 = A(67) Then
            PictureBox1.Image = My.Resources._4_9
        ElseIf t1 = A(68) Then
            PictureBox1.Image = My.Resources._4_10
        ElseIf t1 = A(69) Then
            PictureBox1.Image = My.Resources._4_11
        ElseIf t1 = A(70) Then
            PictureBox1.Image = My.Resources._4_12
        ElseIf t1 = A(71) Then
            PictureBox1.Image = My.Resources._4_13
        ElseIf t1 = A(72) Then
            PictureBox1.Image = My.Resources._4_14
        ElseIf t1 = A(73) Then
            PictureBox1.Image = My.Resources._4_15
        ElseIf t1 = A(74) Then
            PictureBox1.Image = My.Resources._5_1
        ElseIf t1 = A(75) Then
            PictureBox1.Image = My.Resources._5_2
        ElseIf t1 = A(76) Then
            PictureBox1.Image = My.Resources._5_3
        ElseIf t1 = A(77) Then
            PictureBox1.Image = My.Resources._5_4
        ElseIf t1 = A(78) Then
            PictureBox1.Image = My.Resources._5_5
        ElseIf t1 = A(79) Then
            PictureBox1.Image = My.Resources._5_6
        ElseIf t1 = A(80) Then
            PictureBox1.Image = My.Resources._5_7
        ElseIf t1 = A(81) Then
            PictureBox1.Image = My.Resources._5_8
        ElseIf t1 = A(82) Then
            PictureBox1.Image = My.Resources._5_9
        ElseIf t1 = A(83) Then
            PictureBox1.Image = My.Resources._5_10
        ElseIf t1 = A(84) Then
            PictureBox1.Image = My.Resources._6_1
        ElseIf t1 = A(85) Then
            PictureBox1.Image = My.Resources._6_2
        ElseIf t1 = A(86) Then
            PictureBox1.Image = My.Resources._6_3
        ElseIf t1 = A(87) Then
            PictureBox1.Image = My.Resources._6_4
        ElseIf t1 = A(88) Then
            PictureBox1.Image = My.Resources._6_5
        ElseIf t1 = A(89) Then
            PictureBox1.Image = My.Resources._6_6
        ElseIf t1 = A(90) Then
            PictureBox1.Image = My.Resources._6_7
        ElseIf t1 = A(91) Then
            PictureBox1.Image = My.Resources._6_8
        ElseIf t1 = A(92) Then
            PictureBox1.Image = My.Resources._6_9
        ElseIf t1 = A(93) Then
            PictureBox1.Image = My.Resources._6_10
        ElseIf t1 = A(94) Then
            PictureBox1.Image = My.Resources._7_1
        ElseIf t1 = A(95) Then
            T1穿越伊始.Interval = 1000
            PictureBox1.Image = My.Resources._8_1
        ElseIf t1 = A(96) Then
            T1穿越伊始.Interval = 50
            PictureBox1.Image = My.Resources._8_2
        ElseIf t1 = A(97) Then
            PictureBox1.Image = My.Resources._8_3
        ElseIf t1 = A(98) Then
            PictureBox1.Image = My.Resources._8_4
        ElseIf t1 = A(99) Then
            PictureBox1.Image = My.Resources._8_5
        ElseIf t1 = A(100) Then
            PictureBox1.Image = My.Resources._8_6
        ElseIf t1 = A(101) Then
            PictureBox1.Image = My.Resources._8_7
        ElseIf t1 = A(102) Then
            PictureBox1.Image = My.Resources._8_8
        ElseIf t1 = A(103) Then
            PictureBox1.Image = My.Resources._8_9
        ElseIf t1 = A(104) Then
            PictureBox1.Image = My.Resources._8_10
        ElseIf t1 = A(105) Then
            PictureBox1.Image = My.Resources._8_11
        ElseIf t1 = A(106) Then
            PictureBox1.Image = My.Resources._8_12
        ElseIf t1 = A(107) Then
            PictureBox1.Image = My.Resources._8_13
        ElseIf t1 = A(108) Then
            PictureBox1.Image = My.Resources._8_14
        ElseIf t1 = A(109) Then
            PictureBox1.Image = My.Resources._8_15
        ElseIf t1 = A(110) Then
            PictureBox1.Image = My.Resources._8_16
        ElseIf t1 = A(111) Then
            PictureBox1.Image = My.Resources._8_17
        ElseIf t1 = A(112) Then
            PictureBox1.Image = My.Resources._8_18
        ElseIf t1 = A(113) Then
            PictureBox1.Image = My.Resources._8_19
        ElseIf t1 = A(114) Then
            PictureBox1.Image = My.Resources._8_20
        ElseIf t1 = A(115) Then
            PictureBox1.Image = My.Resources._8_21
        ElseIf t1 = A(116) Then
            PictureBox1.Image = My.Resources._8_22
        ElseIf t1 = A(117) Then
            PictureBox1.Image = My.Resources._8_23
        ElseIf t1 = A(118) Then
            PictureBox1.Image = My.Resources._8_24
        ElseIf t1 = A(119) Then
            PictureBox1.Image = My.Resources._8_25
        ElseIf t1 = A(120) Then
            PictureBox1.Image = My.Resources._8_26
        ElseIf t1 = A(121) Then
            PictureBox1.Image = My.Resources._8_27
        ElseIf t1 = A(122) Then
            PictureBox1.Image = My.Resources._8_28
        ElseIf t1 = A(123) Then
            PictureBox1.Image = My.Resources._8_29
        ElseIf t1 = A(124) Then
            PictureBox1.Image = My.Resources._8_30
        ElseIf t1 = A(125) Then
            PictureBox1.Image = My.Resources._8_31
        ElseIf t1 = A(126) Then
            PictureBox1.Image = My.Resources._8_32
        ElseIf t1 = A(127) Then
            PictureBox1.Image = My.Resources._8_33
        ElseIf t1 = A(128) Then
            PictureBox1.Image = My.Resources._8_34
        ElseIf t1 = A(129) Then
            PictureBox1.Image = My.Resources._8_35
        ElseIf t1 = A(130) Then
            PictureBox1.Image = My.Resources._8_36
        ElseIf t1 = A(131) Then
            PictureBox1.Image = My.Resources._8_37
        ElseIf t1 = A(132) Then
            PictureBox1.Image = My.Resources._8_38
        ElseIf t1 = A(133) Then
            PictureBox1.Image = My.Resources._8_39
        ElseIf t1 = A(134) Then
            PictureBox1.Image = My.Resources._8_40
        ElseIf t1 = A(135) Then
            PictureBox1.Image = My.Resources._8_41
        ElseIf t1 = A(136) Then
            PictureBox1.Image = My.Resources._8_42
        ElseIf t1 = A(137) Then
            PictureBox1.Image = My.Resources._8_43
        ElseIf t1 = A(138) Then
            PictureBox1.Image = My.Resources._8_44
        ElseIf t1 = A(139) Then
            PictureBox1.Image = My.Resources._8_45
        ElseIf t1 = A(140) Then
            PictureBox1.Image = My.Resources._8_46
        ElseIf t1 = A(141) Then
            PictureBox1.Image = My.Resources._8_47
        ElseIf t1 = A(142) Then
            PictureBox1.Image = My.Resources._8_48
        ElseIf t1 = A(143) Then
            PictureBox1.Image = My.Resources._8_49
        ElseIf t1 = A(144) Then
            PictureBox1.Image = My.Resources._8_50
        ElseIf t1 = A(145) Then
            PictureBox1.Image = My.Resources._8_51
        ElseIf t1 = A(146) Then
            PictureBox1.Image = My.Resources._8_52
        ElseIf t1 = A(147) Then
            PictureBox1.Image = My.Resources._8_53
        ElseIf t1 = A(148) Then
            PictureBox1.Image = My.Resources._8_54
        ElseIf t1 = A(149) Then
            PictureBox1.Image = My.Resources._8_55
        ElseIf t1 = A(150) Then
            PictureBox1.Image = My.Resources._8_56
        ElseIf t1 = A(151) Then
            PictureBox1.Image = My.Resources._8_57
        ElseIf t1 = A(152) Then
            PictureBox1.Image = My.Resources._8_58
        ElseIf t1 = A(153) Then
            PictureBox1.Image = My.Resources._8_59
        ElseIf t1 = A(154) Then
            PictureBox1.Image = My.Resources._8_60
        ElseIf t1 = A(155) Then
            PictureBox1.Image = My.Resources._8_61
        ElseIf t1 = A(156) Then
            PictureBox1.Image = My.Resources._8_62
        ElseIf t1 = A(157) Then
            PictureBox1.Image = My.Resources._8_63
        ElseIf t1 = A(158) Then
            PictureBox1.Image = My.Resources._8_64
        ElseIf t1 = A(159) Then
            PictureBox1.Image = My.Resources._8_65
        ElseIf t1 = A(160) Then
            PictureBox1.Image = My.Resources._8_66
        ElseIf t1 = A(161) Then
            PictureBox1.Image = My.Resources._8_67
        ElseIf t1 = A(162) Then
            PictureBox1.Image = My.Resources._8_68
        ElseIf t1 = A(163) Then
            PictureBox1.Image = My.Resources._8_69
        ElseIf t1 = A(164) Then
            PictureBox1.Image = My.Resources._8_70
        ElseIf t1 = A(165) Then
            PictureBox1.Image = My.Resources._8_71
        ElseIf t1 = A(166) Then
            PictureBox1.Image = My.Resources._8_72
        ElseIf t1 = A(167) Then
            PictureBox1.Image = My.Resources._8_73
        ElseIf t1 = A(168) Then
            PictureBox1.Image = My.Resources._8_74
        ElseIf t1 = A(169) Then
            PictureBox1.Image = My.Resources._8_75
        ElseIf t1 = A(170) Then
            PictureBox1.Image = My.Resources._8_76
        ElseIf t1 = A(171) Then
            PictureBox1.Image = My.Resources._8_77
        ElseIf t1 = A(172) Then
            PictureBox1.Image = My.Resources._8_78
        ElseIf t1 = A(173) Then
            PictureBox1.Image = My.Resources._8_79
        ElseIf t1 = A(174) Then
            PictureBox1.Image = My.Resources._8_80
        ElseIf t1 = A(175) Then
            PictureBox1.Image = My.Resources._8_81
        ElseIf t1 = A(176) Then
            PictureBox1.Image = My.Resources._8_82
        ElseIf t1 = A(177) Then
            PictureBox1.Image = My.Resources._8_83
        ElseIf t1 = A(178) Then
            PictureBox1.Image = My.Resources._8_84
        ElseIf t1 = A(179) Then
            PictureBox1.Image = My.Resources._8_85
        ElseIf t1 = A(180) Then
            PictureBox1.Image = My.Resources._8_86
        ElseIf t1 = A(181) Then
            PictureBox1.Image = My.Resources._8_87
        ElseIf t1 = A(182) Then
            PictureBox1.Image = My.Resources._8_88
        ElseIf t1 = A(183) Then
            PictureBox1.Image = My.Resources._8_89
        ElseIf t1 = A(184) Then
            PictureBox1.Image = My.Resources._8_90
        ElseIf t1 = A(185) Then
            PictureBox1.Image = My.Resources._8_91
        ElseIf t1 = A(186) Then
            PictureBox1.Image = My.Resources._8_92
        ElseIf t1 = A(187) Then
            PictureBox1.Image = My.Resources._8_93
        ElseIf t1 = A(188) Then
            PictureBox1.Image = My.Resources._8_94
        ElseIf t1 = A(189) Then
            PictureBox1.Image = My.Resources._8_95
        ElseIf t1 = A(190) Then
            PictureBox1.Image = My.Resources._9_19
            T1穿越伊始.Interval = 100
        ElseIf t1 = A(191) Then
            PictureBox1.Image = My.Resources._9_18
        ElseIf t1 = A(192) Then
            PictureBox1.Image = My.Resources._9_17
        ElseIf t1 = A(193) Then
            PictureBox1.Image = My.Resources._9_16
        ElseIf t1 = A(194) Then
            PictureBox1.Image = My.Resources._9_15
        ElseIf t1 = A(195) Then
            PictureBox1.Image = My.Resources._9_14
        ElseIf t1 = A(196) Then
            PictureBox1.Image = My.Resources._9_13
        ElseIf t1 = A(197) Then
            PictureBox1.Image = My.Resources._9_12
        ElseIf t1 = A(198) Then
            PictureBox1.Image = My.Resources._9_11
        ElseIf t1 = A(199) Then
            PictureBox1.Image = My.Resources._9_10
        ElseIf t1 = A(200) Then
            PictureBox1.Image = My.Resources._9_9
        ElseIf t1 = A(201) Then
            PictureBox1.Image = My.Resources._9_8
        ElseIf t1 = A(202) Then
            PictureBox1.Image = My.Resources._9_7
        ElseIf t1 = A(203) Then
            PictureBox1.Image = My.Resources._9_6
        ElseIf t1 = A(204) Then
            PictureBox1.Image = My.Resources._9_5
        ElseIf t1 = A(205) Then
            PictureBox1.Image = My.Resources._9_4
        ElseIf t1 = A(206) Then
            PictureBox1.Image = My.Resources._9_3
        ElseIf t1 = A(207) Then
            PictureBox1.Image = My.Resources._9_2
        ElseIf t1 = A(208) Then
            PictureBox1.Image = My.Resources._9_1
        ElseIf t1 = A(209) Then
            PictureBox1.Image = My.Resources._10_1
        ElseIf t1 = A(210) Then
            PictureBox1.Image = My.Resources._10_2
        ElseIf t1 = A(211) Then
            PictureBox1.Image = My.Resources._10_3
        ElseIf t1 = A(212) Then
            PictureBox1.Image = My.Resources._10_4
        ElseIf t1 = A(213) Then
            PictureBox1.Image = My.Resources._10_5
        ElseIf t1 = A(214) Then
            PictureBox1.Image = My.Resources._10_6
        ElseIf t1 = A(215) Then
            PictureBox1.Image = My.Resources._10_7
        ElseIf t1 = A(216) Then
            PictureBox1.Image = My.Resources._10_8
        ElseIf t1 = A(217) Then
            PictureBox1.Image = My.Resources._10_9
        ElseIf t1 = A(218) Then
            PictureBox1.Image = My.Resources._10_10
        ElseIf t1 = A(219) Then
            PictureBox1.Image = My.Resources._10_11
        ElseIf t1 = A(220) Then
            PictureBox1.Image = My.Resources._10_12
        ElseIf t1 = A(221) Then
            PictureBox1.Image = My.Resources._10_13
        ElseIf t1 = A(222) Then
            PictureBox1.Image = My.Resources._10_14
        ElseIf t1 = A(223) Then
            PictureBox1.Image = My.Resources._10_15
        ElseIf t1 = A(224) Then
            PictureBox1.Image = My.Resources._10_16
        ElseIf t1 = A(225) Then
            PictureBox1.Image = My.Resources._10_17
        ElseIf t1 = A(226) Then
            PictureBox1.Image = My.Resources._10_18
        ElseIf t1 = A(227) Then
            PictureBox1.Image = My.Resources._10_19
        ElseIf t1 = A(228) Then
            PictureBox1.Image = My.Resources._10_20
        ElseIf t1 = A(229) Then
            PictureBox1.Image = My.Resources._10_21
        ElseIf t1 = A(230) Then
            PictureBox1.Image = My.Resources._10_22
        ElseIf t1 = A(231) Then
            PictureBox1.Image = My.Resources._10_23
        ElseIf t1 = A(232) Then
            PictureBox1.Image = My.Resources._10_24
        ElseIf t1 = A(233) Then
            PictureBox1.Image = My.Resources._11_1
        ElseIf t1 = A(234) Then
            PictureBox1.Image = My.Resources._11_2
        ElseIf t1 = A(235) Then
            PictureBox1.Image = My.Resources._11_3
        ElseIf t1 = A(236) Then
            PictureBox1.Image = My.Resources._11_4
        ElseIf t1 = A(237) Then
            PictureBox1.Image = My.Resources._11_5
        ElseIf t1 = A(238) Then
            PictureBox1.Image = My.Resources._11_6
        ElseIf t1 = A(239) Then
            PictureBox1.Image = My.Resources._11_7
        ElseIf t1 = A(240) Then
            PictureBox1.Image = My.Resources._11_8
        ElseIf t1 = A(241) Then
            PictureBox1.Image = My.Resources._11_9
        ElseIf t1 = A(242) Then
            PictureBox1.Image = My.Resources._11_10
        ElseIf t1 = A(243) Then
            PictureBox1.Image = My.Resources._11_11
        ElseIf t1 = A(244) Then
            PictureBox1.Image = My.Resources.h1
        ElseIf t1 = A(245) Then
            PictureBox1.Image = My.Resources.h2
        ElseIf t1 = A(246) Then
            PictureBox1.Image = My.Resources.h3
        ElseIf t1 = A(247) Then
            PictureBox1.Image = My.Resources.h4
        ElseIf t1 = A(248) Then
            PictureBox1.Image = My.Resources.h5
        ElseIf t1 = A(249) Then
            PictureBox1.Image = My.Resources.h6
        ElseIf t1 = A(250) Then
            PictureBox1.Image = My.Resources.h7
        ElseIf t1 = A(251) Then
            PictureBox1.Image = My.Resources.h8
        ElseIf t1 = A(252) Then
            PictureBox1.Image = My.Resources.h9
        ElseIf t1 = A(253) Then
            PictureBox1.Image = My.Resources.h10
        ElseIf t1 = A(254) Then
            PictureBox1.Image = My.Resources.h11
        ElseIf t1 = A(255) Then
            PictureBox1.Image = My.Resources.h12
        ElseIf t1 = A(256) Then
            PictureBox1.Image = My.Resources.h13
        ElseIf t1 = A(257) Then
            PictureBox1.Image = My.Resources.h14
        ElseIf t1 = A(258) Then
            PictureBox1.Image = My.Resources.h15
        ElseIf t1 = A(259) Then
            PictureBox1.Image = My.Resources.h16
        ElseIf t1 = A(260) Then
            PictureBox1.Image = My.Resources.h17
        ElseIf t1 = A(261) Then
            PictureBox1.Image = My.Resources.h18
        ElseIf t1 = A(262) Then
            PictureBox1.Image = My.Resources.h19
        ElseIf t1 = A(263) Then
            PictureBox1.Image = My.Resources.h20
        ElseIf t1 = A(264) Then
            PictureBox1.Image = My.Resources.h21
        ElseIf t1 = A(265) Then
            PictureBox1.Image = My.Resources.h22
        ElseIf t1 = A(266) Then
            PictureBox1.Image = My.Resources.h23
        ElseIf t1 = A(267) Then
            PictureBox1.Image = My.Resources.h24
        ElseIf t1 = A(268) Then
            PictureBox1.Image = My.Resources.h25
        ElseIf t1 = A(269) Then
            PictureBox1.Image = My.Resources.h26
        ElseIf t1 = A(270) Then
            PictureBox1.Image = My.Resources.h27
        ElseIf t1 = A(271) Then
            PictureBox1.Image = My.Resources.h28
        ElseIf t1 = A(272) Then
            PictureBox1.Image = My.Resources.h29
        ElseIf t1 = A(273) Then
            PictureBox1.Image = My.Resources.h30
        ElseIf t1 = A(274) Then
            PictureBox1.Image = My.Resources.h31
        ElseIf t1 = A(275) Then
            PictureBox1.Image = My.Resources.h32
        ElseIf t1 = A(276) Then
            PictureBox1.Image = My.Resources.h33
        ElseIf t1 = A(277) Then
            PictureBox1.Image = My.Resources.h34
        ElseIf t1 = A(278) Then
            PictureBox1.Image = My.Resources.h35
        ElseIf t1 = A(279) Then
            PictureBox1.Image = My.Resources.h36
        ElseIf t1 = A(280) Then
            PictureBox1.Image = My.Resources.h37
        ElseIf t1 = A(281) Then
            PictureBox1.Image = My.Resources.h38
        ElseIf t1 = A(282) Then
            PictureBox1.Image = My.Resources.h39
        ElseIf t1 = A(283) Then
            PictureBox1.Image = My.Resources.h40
        ElseIf t1 = A(284) Then
            PictureBox1.Image = My.Resources.h41
        ElseIf t1 = A(285) Then
            PictureBox1.Image = My.Resources.h42
        ElseIf t1 = A(286) Then
            PictureBox1.Image = My.Resources.h43
        ElseIf t1 = A(287) Then
            PictureBox1.Image = My.Resources.h44
        ElseIf t1 = A(288) Then
            PictureBox1.Image = My.Resources.h45
        ElseIf t1 = A(289) Then
            PictureBox1.Image = My.Resources.h46
        ElseIf t1 = A(290) Then
            PictureBox1.Image = My.Resources.h47
        ElseIf t1 = A(291) Then
            PictureBox1.Image = My.Resources.h48
        ElseIf t1 = A(292) Then
            PictureBox1.Image = My.Resources.h49
        ElseIf t1 = A(293) Then
            PictureBox1.Image = My.Resources.h50
        ElseIf t1 = A(294) Then
            PictureBox1.Image = My.Resources.h51
        ElseIf t1 = A(295) Then
            PictureBox1.Image = My.Resources.h52
        ElseIf t1 = A(296) Then
            PictureBox1.Image = My.Resources.h53
        ElseIf t1 = A(297) Then
            PictureBox1.Image = My.Resources.h54
        ElseIf t1 = A(298) Then
            PictureBox1.Image = My.Resources.h55
        ElseIf t1 = A(299) Then
            PictureBox1.Image = My.Resources.h56
        ElseIf t1 = A(300) Then
            PictureBox1.Image = My.Resources.h57
        ElseIf t1 = A(301) Then
            PictureBox1.Image = My.Resources.h58
        ElseIf t1 = A(302) Then
            PictureBox1.Image = My.Resources.h59
        ElseIf t1 = A(303) Then
            PictureBox1.Image = My.Resources.h60
        ElseIf t1 = A(304) Then
            PictureBox1.Image = My.Resources.h61
        ElseIf t1 = A(305) Then
            PictureBox1.Image = My.Resources.h62
        ElseIf t1 = A(306) Then
            PictureBox1.Image = My.Resources.h63
        ElseIf t1 = A(307) Then
            PictureBox1.Image = My.Resources.h64
        ElseIf t1 = A(308) Then
            PictureBox1.Image = My.Resources.h65
        ElseIf t1 = A(309) Then
            PictureBox1.Image = My.Resources.h66
        ElseIf t1 = A(310) Then
            PictureBox1.Image = My.Resources.h67
        ElseIf t1 = A(311) Then
            PictureBox1.Image = My.Resources.h68
        ElseIf t1 = A(312) Then
            PictureBox1.Image = My.Resources.h69
        ElseIf t1 = A(313) Then
            PictureBox1.Image = My.Resources.h70
        ElseIf t1 = A(314) Then
            PictureBox1.Image = My.Resources.h71
        ElseIf t1 = A(315) Then
            PictureBox1.Image = My.Resources.h72
        ElseIf t1 = A(316) Then
            PictureBox1.Image = My.Resources.h73
        ElseIf t1 = A(317) Then
            PictureBox1.Image = My.Resources.h74
        ElseIf t1 = A(318) Then
            PictureBox1.Image = My.Resources.h75
        ElseIf t1 = A(319) Then
            PictureBox1.Image = My.Resources.h76
        ElseIf t1 = A(320) Then
            PictureBox1.Image = My.Resources.h77
        ElseIf t1 = A(321) Then
            PictureBox1.Image = My.Resources.h78
        ElseIf t1 = A(322) Then
            PictureBox1.Image = My.Resources.h79
        ElseIf t1 = A(323) Then
            PictureBox1.Image = My.Resources.h80
        ElseIf t1 = A(324) Then
            PictureBox1.Image = My.Resources.h81
        ElseIf t1 = A(325) Then
            PictureBox1.Image = My.Resources.h82
        ElseIf t1 = A(326) Then
            PictureBox1.Image = My.Resources.h83
        ElseIf t1 = A(327) Then
            PictureBox1.Image = My.Resources.h84
        ElseIf t1 = A(328) Then
            PictureBox1.Image = My.Resources.h85
        ElseIf t1 = A(329) Then
            PictureBox1.Image = My.Resources.h86
        ElseIf t1 = A(330) Then
            PictureBox1.Image = My.Resources.h87
        ElseIf t1 = A(331) Then
            PictureBox1.Image = My.Resources.h88
        ElseIf t1 = A(332) Then
            PictureBox1.Image = My.Resources.h89
        ElseIf t1 = A(333) Then
            PictureBox1.Image = My.Resources.h90
        ElseIf t1 = A(334) Then
            PictureBox1.Image = My.Resources.h91
        ElseIf t1 = A(335) Then
            PictureBox1.Image = My.Resources.h92
        ElseIf t1 = A(336) Then
            PictureBox1.Image = My.Resources.h93
        ElseIf t1 = A(337) Then
            PictureBox1.Image = My.Resources.h94
        ElseIf t1 = A(338) Then
            PictureBox1.Image = My.Resources.h95
        ElseIf t1 = A(339) Then
            PictureBox1.Image = My.Resources.h96
        ElseIf t1 = A(340) Then
            PictureBox1.Image = My.Resources.h97
        ElseIf t1 = A(341) Then
            PictureBox1.Image = My.Resources.h98
        ElseIf t1 = A(342) Then
            PictureBox1.Image = My.Resources.h99
        ElseIf t1 = A(343) Then
            PictureBox1.Image = My.Resources.h100
        ElseIf t1 = A(344) Then
            PictureBox1.Image = My.Resources.h101
        ElseIf t1 = A(345) Then
            PictureBox1.Image = My.Resources.h102
        ElseIf t1 = A(346) Then
            PictureBox1.Image = My.Resources.h103
        ElseIf t1 = A(347) Then
            PictureBox1.Image = My.Resources.h104
        ElseIf t1 = A(348) Then
            PictureBox1.Image = My.Resources.h105
        ElseIf t1 = A(349) Then
            PictureBox1.Image = My.Resources.h106
        ElseIf t1 = A(350) Then
            PictureBox1.Image = My.Resources.h107
        ElseIf t1 = A(351) Then
            PictureBox1.Image = My.Resources.h108
        ElseIf t1 = A(352) Then
            PictureBox1.Image = My.Resources.h109
        ElseIf t1 = A(353) Then
            PictureBox1.Image = My.Resources.h110
        ElseIf t1 = A(354) Then
            PictureBox1.Image = My.Resources.h111
        ElseIf t1 = A(355) Then
            PictureBox1.Image = My.Resources.h112
        ElseIf t1 = A(356) Then
            PictureBox1.Image = My.Resources.h113
        ElseIf t1 = A(357) Then
            PictureBox1.Image = My.Resources.h114
        ElseIf t1 = A(358) Then
            PictureBox1.Image = My.Resources.h115
        ElseIf t1 = A(359) Then
            PictureBox1.Image = My.Resources.h116
        ElseIf t1 = A(360) Then
            PictureBox1.Image = My.Resources.h117
        ElseIf t1 = A(361) Then
            PictureBox1.Image = My.Resources.h118
        ElseIf t1 = A(362) Then
            PictureBox1.Image = My.Resources.h119
        ElseIf t1 = A(363) Then
            PictureBox1.Image = My.Resources.h120
        ElseIf t1 = A(364) Then
            PictureBox1.Image = My.Resources.h121
        ElseIf t1 = A(365) Then
            PictureBox1.Image = My.Resources.h122
        ElseIf t1 = A(366) Then
            PictureBox1.Image = My.Resources.h123
        ElseIf t1 = A(367) Then
            PictureBox1.Image = My.Resources.h124
        ElseIf t1 = A(368) Then
            PictureBox1.Image = My.Resources.h125
        ElseIf t1 = A(369) Then
            PictureBox1.Image = My.Resources.h126
        ElseIf t1 = A(370) Then
            PictureBox1.Image = My.Resources.h127
        ElseIf t1 = A(371) Then
            PictureBox1.Image = My.Resources.h128
        ElseIf t1 = A(372) Then
            PictureBox1.Image = My.Resources.h129
        ElseIf t1 = A(373) Then
            PictureBox1.Image = My.Resources.h130
        ElseIf t1 = A(374) Then
            PictureBox1.Image = My.Resources.h131
        ElseIf t1 = A(375) Then
            PictureBox1.Image = My.Resources.h132
        ElseIf t1 = A(376) Then
            PictureBox1.Image = My.Resources.h133
        ElseIf t1 = A(377) Then
            PictureBox1.Image = My.Resources.h134
        ElseIf t1 = A(378) Then
            PictureBox1.Image = My.Resources.h135
        ElseIf t1 = A(379) Then
            PictureBox1.Image = My.Resources.h136
        ElseIf t1 = A(380) Then
            PictureBox1.Image = My.Resources.h137
        ElseIf t1 = A(381) Then
            PictureBox1.Image = My.Resources.h138
        ElseIf t1 = A(382) Then
            PictureBox1.Image = My.Resources.h139
        ElseIf t1 = A(383) Then
            PictureBox1.Image = My.Resources.h140
        ElseIf t1 = A(384) Then
            PictureBox1.Image = My.Resources.h141
        ElseIf t1 = A(385) Then
            PictureBox1.Image = My.Resources.h142
        ElseIf t1 = A(386) Then
            PictureBox1.Image = My.Resources.h143
        ElseIf t1 = A(387) Then
            PictureBox1.Image = My.Resources.h144
        ElseIf t1 = A(388) Then
            PictureBox1.Image = My.Resources.h145
        ElseIf t1 = A(389) Then
            PictureBox1.Image = My.Resources.h146
        ElseIf t1 = A(390) Then
            PictureBox1.Image = My.Resources.h147
        ElseIf t1 = A(391) Then
            PictureBox1.Image = My.Resources.h148
        ElseIf t1 = A(392) Then
            PictureBox1.Image = My.Resources.h149
        ElseIf t1 = A(393) Then
            PictureBox1.Image = My.Resources.h150
        ElseIf t1 = A(394) Then
            PictureBox1.Image = My.Resources.h151
        ElseIf t1 = A(395) Then
            PictureBox1.Image = My.Resources.h152
        ElseIf t1 = A(396) Then
            PictureBox1.Image = My.Resources.h153
        ElseIf t1 = A(397) Then
            PictureBox1.Image = My.Resources.h154
        ElseIf t1 = A(398) Then
            PictureBox1.Image = My.Resources.h155
        ElseIf t1 = A(399) Then
            PictureBox1.Image = My.Resources.h156
        ElseIf t1 = A(400) Then
            PictureBox1.Image = My.Resources.h157
        ElseIf t1 = A(401) Then
            PictureBox1.Image = My.Resources.h158
        ElseIf t1 = A(402) Then
            PictureBox1.Image = My.Resources.h159
        ElseIf t1 = A(403) Then
            PictureBox1.Image = My.Resources.h160
        ElseIf t1 = A(404) Then
            PictureBox1.Image = My.Resources.h161
        ElseIf t1 = A(405) Then
            PictureBox1.Image = My.Resources.h162
        ElseIf t1 = A(406) Then
            PictureBox1.Image = My.Resources.h163
        ElseIf t1 = A(407) Then
            PictureBox1.Image = My.Resources.h164
        ElseIf t1 = A(408) Then
            PictureBox1.Image = My.Resources.h165
        ElseIf t1 = A(409) Then
            PictureBox1.Image = My.Resources.h166
        ElseIf t1 = A(410) Then
            PictureBox1.Image = My.Resources.h167
        ElseIf t1 = A(411) Then
            PictureBox1.Image = My.Resources.h168
        ElseIf t1 = A(412) Then
            PictureBox1.Image = My.Resources.h169
        ElseIf t1 = A(413) Then
            PictureBox1.Image = My.Resources.h170
        ElseIf t1 = A(414) Then
            PictureBox1.Image = My.Resources.h171
        ElseIf t1 = A(415) Then
            PictureBox1.Image = My.Resources.h172
        ElseIf t1 = A(416) Then
            PictureBox1.Image = My.Resources.h173
        ElseIf t1 = A(417) Then
            PictureBox1.Image = My.Resources.h174
        ElseIf t1 = A(418) Then
            PictureBox1.Image = My.Resources.h175
        ElseIf t1 = A(419) Then
            PictureBox1.Image = My.Resources.h176
        ElseIf t1 = A(420) Then
            PictureBox1.Image = My.Resources.h177
        ElseIf t1 = A(421) Then
            PictureBox1.Image = My.Resources.h178
        ElseIf t1 = A(422) Then
            PictureBox1.Image = My.Resources.h179
        ElseIf t1 = A(423) Then
            PictureBox1.Image = My.Resources.h180
        ElseIf t1 = A(424) Then
            PictureBox1.Image = My.Resources.h181
        ElseIf t1 = A(425) Then
            PictureBox1.Image = My.Resources.h182
        ElseIf t1 = A(426) Then
            PictureBox1.Image = My.Resources.h183
        ElseIf t1 = A(427) Then
            PictureBox1.Image = My.Resources.h184
        ElseIf t1 = A(428) Then
            PictureBox1.Image = My.Resources.h185
        ElseIf t1 = A(429) Then
            PictureBox1.Image = My.Resources.h186
        ElseIf t1 = A(430) Then
            PictureBox1.Image = My.Resources.h187
        ElseIf t1 = A(431) Then
            PictureBox1.Image = My.Resources.h188
        ElseIf t1 = A(432) Then
            PictureBox1.Image = My.Resources.h189
        ElseIf t1 = A(433) Then
            PictureBox1.Image = My.Resources.h190
        ElseIf t1 = A(434) Then
            PictureBox1.Image = My.Resources.h191
        ElseIf t1 = A(435) Then
            PictureBox1.Image = My.Resources.h192
        ElseIf t1 = A(436) Then
            PictureBox1.Image = My.Resources.h193
        ElseIf t1 = A(437) Then
            PictureBox1.Image = My.Resources.h194
        ElseIf t1 = A(438) Then
            PictureBox1.Image = My.Resources.h195
        ElseIf t1 = A(439) Then
            PictureBox1.Image = My.Resources.h196
        ElseIf t1 = A(440) Then
            PictureBox1.Image = My.Resources.h197
        ElseIf t1 = A(441) Then
            PictureBox1.Image = My.Resources.h198
        ElseIf t1 = A(442) Then
            PictureBox1.Image = My.Resources.h199
        ElseIf t1 = A(443) Then
            PictureBox1.Image = My.Resources.h200
        ElseIf t1 = A(444) Then
            PictureBox1.Image = My.Resources.h201
        ElseIf t1 = A(445) Then
            PictureBox1.Image = My.Resources.h202
        ElseIf t1 = A(446) Then
            PictureBox1.Image = My.Resources.h203
        ElseIf t1 = A(447) Then
            PictureBox1.Image = My.Resources.h204
        ElseIf t1 = A(448) Then
            PictureBox1.Image = My.Resources.h205
        ElseIf t1 = A(449) Then
            PictureBox1.Image = My.Resources.h206
        ElseIf t1 = A(450) Then
            PictureBox1.Image = My.Resources.h207
        ElseIf t1 = A(451) Then
            PictureBox1.Image = My.Resources.h208
        ElseIf t1 = A(452) Then
            PictureBox1.Image = My.Resources.h209
        ElseIf t1 = A(453) Then
            PictureBox1.Image = My.Resources.h210
        ElseIf t1 = A(454) Then
            PictureBox1.Image = My.Resources.h211
        ElseIf t1 = A(455) Then
            PictureBox1.Image = My.Resources.h212
        ElseIf t1 = A(456) Then
            PictureBox1.Image = My.Resources.h213
        ElseIf t1 = A(457) Then
            PictureBox1.Image = My.Resources.h214
        ElseIf t1 = A(458) Then
            PictureBox1.Image = My.Resources.h215
        ElseIf t1 = A(459) Then
            PictureBox1.Image = My.Resources.h216
        ElseIf t1 = A(460) Then
            PictureBox1.Image = My.Resources.h217
        ElseIf t1 = A(461) Then
            PictureBox1.Image = My.Resources.h218
        ElseIf t1 = A(462) Then
            PictureBox1.Image = My.Resources.h219
        ElseIf t1 = A(463) Then
            PictureBox1.Image = My.Resources.h220
        ElseIf t1 = A(464) Then
            PictureBox1.Image = My.Resources.h221
        ElseIf t1 = A(465) Then
            PictureBox1.Image = My.Resources.h222
        ElseIf t1 = A(466) Then
            PictureBox1.Image = My.Resources.h223
        ElseIf t1 = A(467) Then
            PictureBox1.Image = My.Resources.h224
        ElseIf t1 = A(468) Then
            PictureBox1.Image = My.Resources.h225
        ElseIf t1 = A(469) Then
            PictureBox1.Image = My.Resources.h226
        ElseIf t1 = A(470) Then
            PictureBox1.Image = My.Resources.h227
        ElseIf t1 = A(471) Then
            PictureBox1.Image = My.Resources.h228
        ElseIf t1 = A(472) Then
            PictureBox1.Image = My.Resources.h229
        ElseIf t1 = A(473) Then
            PictureBox1.Image = My.Resources.h230
        ElseIf t1 = A(474) Then
            PictureBox1.Image = My.Resources.h231
        ElseIf t1 = A(475) Then
            PictureBox1.Image = My.Resources.h232
        ElseIf t1 = A(476) Then
            PictureBox1.Image = My.Resources.h233
        ElseIf t1 = A(477) Then
            PictureBox1.Image = My.Resources.h234
        ElseIf t1 = A(478) Then
            PictureBox1.Image = My.Resources.h235
        ElseIf t1 = A(479) Then
            PictureBox1.Image = My.Resources.h236
        ElseIf t1 = A(480) Then
            PictureBox1.Image = My.Resources.h237
        ElseIf t1 = A(481) Then
            PictureBox1.Image = My.Resources.h238
        ElseIf t1 = A(482) Then
            PictureBox1.Image = My.Resources.h239
        ElseIf t1 = A(483) Then
            PictureBox1.Image = My.Resources.h240
        ElseIf t1 = A(484) Then
            PictureBox1.Image = My.Resources.h241
        ElseIf t1 = A(485) Then
            PictureBox1.Image = My.Resources.h242
        ElseIf t1 = A(486) Then
            PictureBox1.Image = My.Resources.h243
        ElseIf t1 = A(487) Then
            PictureBox1.Image = My.Resources.h244
        ElseIf t1 = A(488) Then
            PictureBox1.Image = My.Resources.h245
        ElseIf t1 = A(489) Then
            PictureBox1.Image = My.Resources.h246
        ElseIf t1 = A(490) Then
            PictureBox1.Image = My.Resources.h247
        ElseIf t1 = A(491) Then
            PictureBox1.Image = My.Resources.h248
        ElseIf t1 = A(492) Then
            PictureBox1.Image = My.Resources.h249
        ElseIf t1 = A(493) Then
            PictureBox1.Image = My.Resources.h250
        ElseIf t1 = A(494) Then
            PictureBox1.Image = My.Resources.h251
        ElseIf t1 = A(495) Then
            PictureBox1.Image = My.Resources.h252
        ElseIf t1 = A(496) Then
            PictureBox1.Image = My.Resources.h253
        ElseIf t1 = A(497) Then
            PictureBox1.Image = My.Resources.h254
        ElseIf t1 = A(498) Then
            PictureBox1.Image = My.Resources.h255
        ElseIf t1 = A(499) Then
            PictureBox1.Image = My.Resources.h256
        ElseIf t1 = A(500) Then
            PictureBox1.Image = My.Resources.h257
        ElseIf t1 = A(501) Then
            PictureBox1.Image = My.Resources.h258
        ElseIf t1 = A(502) Then
            PictureBox1.Image = My.Resources.h259
        ElseIf t1 = A(503) Then
            PictureBox1.Image = My.Resources.h260
        ElseIf t1 = A(504) Then
            PictureBox1.Image = My.Resources.h261
        ElseIf t1 = A(505) Then
            PictureBox1.Image = My.Resources.h262
        ElseIf t1 = A(506) Then
            PictureBox1.Image = My.Resources.h263
        ElseIf t1 = A(507) Then
            PictureBox1.Image = My.Resources.h264
        ElseIf t1 = A(508) Then
            PictureBox1.Image = My.Resources.h265
        ElseIf t1 = A(509) Then
            PictureBox1.Image = My.Resources.h266
        ElseIf t1 = A(510) Then
            PictureBox1.Image = My.Resources.h267
        ElseIf t1 = A(511) Then
            PictureBox1.Image = My.Resources.h268
        ElseIf t1 = A(512) Then
            PictureBox1.Image = My.Resources.h269
        ElseIf t1 = A(513) Then
            PictureBox1.Image = My.Resources.h270
        ElseIf t1 = A(514) Then
            PictureBox1.Image = My.Resources.h271
        ElseIf t1 = A(515) Then
            PictureBox1.Image = My.Resources.h272
        ElseIf t1 = A(516) Then
            PictureBox1.Image = My.Resources.h273
        ElseIf t1 = A(517) Then
            PictureBox1.Image = My.Resources.h274
        ElseIf t1 = A(518) Then
            PictureBox1.Image = My.Resources.h275
        ElseIf t1 = A(519) Then
            PictureBox1.Image = My.Resources.h276
        ElseIf t1 = A(520) Then
            PictureBox1.Image = My.Resources.h277
        ElseIf t1 = A(521) Then
            PictureBox1.Image = My.Resources.h278
        ElseIf t1 = A(522) Then
            PictureBox1.Image = My.Resources.h279
        ElseIf t1 = A(523) Then
            PictureBox1.Image = My.Resources.h280
        ElseIf t1 = A(524) Then
            PictureBox1.Image = My.Resources.h281
        ElseIf t1 = A(525) Then
            PictureBox1.Image = My.Resources.h282
        ElseIf t1 = A(526) Then
            PictureBox1.Image = My.Resources.h283
        ElseIf t1 = A(527) Then
            PictureBox1.Image = My.Resources.h284
        ElseIf t1 = A(528) Then
            PictureBox1.Image = My.Resources.h285
        ElseIf t1 = A(529) Then
            PictureBox1.Image = My.Resources.h286
        ElseIf t1 = A(530) Then
            PictureBox1.Image = My.Resources.h287
        ElseIf t1 = A(531) Then
            PictureBox1.Image = My.Resources.h288
        ElseIf t1 = A(532) Then
            PictureBox1.Image = My.Resources.h289
        ElseIf t1 = A(533) Then
            PictureBox1.Image = My.Resources.h290
        ElseIf t1 = A(534) Then
            PictureBox1.Image = My.Resources.h291
        ElseIf t1 = A(535) Then
            PictureBox1.Image = My.Resources.h292
        ElseIf t1 = A(536) Then
            PictureBox1.Image = My.Resources.h293
        ElseIf t1 = A(537) Then
            PictureBox1.Image = My.Resources.h294
        ElseIf t1 = A(538) Then
            PictureBox1.Image = My.Resources.h295
        ElseIf t1 = A(539) Then
            PictureBox1.Image = My.Resources.h296
        ElseIf t1 = A(540) Then
            PictureBox1.Image = My.Resources.h297
        ElseIf t1 = A(541) Then
            PictureBox1.Image = My.Resources.h298
            PlaylightSoundResource()
        ElseIf t1 = A(542) Then
            PictureBox1.Image = My.Resources.h299
        ElseIf t1 = A(543) Then
            PictureBox1.Image = My.Resources.h300
        ElseIf t1 = A(544) Then
            PictureBox1.Image = My.Resources.h301
        ElseIf t1 = A(545) Then
            PictureBox1.Image = My.Resources.h302
        ElseIf t1 = A(546) Then
            PictureBox1.Image = My.Resources.h303
        ElseIf t1 = A(547) Then
            PictureBox1.Image = My.Resources.h304
        ElseIf t1 = A(548) Then
            PictureBox1.Image = My.Resources.h305
        ElseIf t1 = A(549) Then
            PictureBox1.Image = My.Resources.h306
        ElseIf t1 = A(550) Then
            PictureBox1.Image = My.Resources.h307
        ElseIf t1 = A(551) Then
            PictureBox1.Image = My.Resources.h308
        ElseIf t1 = A(552) Then
            PictureBox1.Image = My.Resources.h309
        ElseIf t1 = A(553) Then
            PictureBox1.Image = My.Resources.h310
        ElseIf t1 = A(554) Then
            PictureBox1.Image = My.Resources.h311
        ElseIf t1 = A(555) Then
            PictureBox1.Image = My.Resources.h312
        ElseIf t1 = A(556) Then
            PictureBox1.Image = My.Resources.h313
        ElseIf t1 = A(557) Then
            PictureBox1.Image = My.Resources.h314
        ElseIf t1 = A(558) Then
            PictureBox1.Image = My.Resources.h315
        ElseIf t1 = A(559) Then
            PictureBox1.Image = My.Resources.h316
        ElseIf t1 = A(560) Then
            PictureBox1.Image = My.Resources.h317
        ElseIf t1 = A(561) Then
            PictureBox1.Image = My.Resources.h318
        ElseIf t1 = A(562) Then
            PictureBox1.Image = My.Resources.h319
        ElseIf t1 = A(563) Then
            PictureBox1.Image = My.Resources.h320
        ElseIf t1 = A(564) Then
            PictureBox1.Image = My.Resources.h321
        ElseIf t1 = A(565) Then
            PictureBox1.Image = My.Resources.h322
        ElseIf t1 = A(566) Then
            PictureBox1.Image = My.Resources.h323
        ElseIf t1 = A(567) Then
            PictureBox1.Image = My.Resources.h324
        ElseIf t1 = A(568) Then
            PictureBox1.Image = My.Resources.h325
        ElseIf t1 = A(569) Then
            PictureBox1.Image = My.Resources.h326
        ElseIf t1 = A(570) Then
            PictureBox1.Image = My.Resources.h327
        ElseIf t1 = A(571) Then
            PictureBox1.Image = My.Resources.h328
        ElseIf t1 = A(572) Then
            PictureBox1.Image = My.Resources.h329
        ElseIf t1 = A(573) Then
            PictureBox1.Image = My.Resources.h330
        ElseIf t1 = A(574) Then
            PictureBox1.Image = My.Resources.h331
        ElseIf t1 = A(575) Then
            'ShowCursor(1)
            Windows.Forms.Cursor.Show()
            PictureBox1.Image = Nothing
        ElseIf t1 = A(576) Then
            T1穿越伊始.Enabled = False
            Close()

        End If
    End Sub

End Class
